language: node_js
node_js:
    - "7.0"
env:
    - CXX=g++-4.8
addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

branches:
    only:
        - master

before_script:
    - npm install -g firebase-tools

script:
    - echo 'Hello Firebase'

after_success:
    - firebase deploy --token=${FIREBASE_API_TOKEN}